# Generated by Django 4.2 on 2025-05-13 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0002_add_extra_photos'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='property',
            name='latitude',
        ),
        migrations.RemoveField(
            model_name='property',
            name='longitude',
        ),
        migrations.AddField(
            model_name='property',
            name='photo_10',
            field=models.ImageField(blank=True, null=True, upload_to='properties/', verbose_name='Фото 10'),
        ),
        migrations.AddField(
            model_name='property',
            name='photo_7',
            field=models.ImageField(blank=True, null=True, upload_to='properties/', verbose_name='Фото 7'),
        ),
        migrations.AddField(
            model_name='property',
            name='photo_8',
            field=models.ImageField(blank=True, null=True, upload_to='properties/', verbose_name='Фото 8'),
        ),
        migrations.AddField(
            model_name='property',
            name='photo_9',
            field=models.ImageField(blank=True, null=True, upload_to='properties/', verbose_name='Фото 9'),
        ),
        migrations.AlterField(
            model_name='property',
            name='main_photo',
            field=models.ImageField(upload_to='properties/', verbose_name='Главное фото'),
        ),
        migrations.AlterField(
            model_name='property',
            name='photo_1',
            field=models.ImageField(blank=True, null=True, upload_to='properties/', verbose_name='Фото 1'),
        ),
        migrations.AlterField(
            model_name='property',
            name='photo_2',
            field=models.ImageField(blank=True, null=True, upload_to='properties/', verbose_name='Фото 2'),
        ),
        migrations.AlterField(
            model_name='property',
            name='photo_3',
            field=models.ImageField(blank=True, null=True, upload_to='properties/', verbose_name='Фото 3'),
        ),
        migrations.AlterField(
            model_name='property',
            name='photo_4',
            field=models.ImageField(blank=True, null=True, upload_to='properties/', verbose_name='Фото 4'),
        ),
        migrations.AlterField(
            model_name='property',
            name='photo_5',
            field=models.ImageField(blank=True, null=True, upload_to='properties/', verbose_name='Фото 5'),
        ),
        migrations.AlterField(
            model_name='property',
            name='photo_6',
            field=models.ImageField(blank=True, null=True, upload_to='properties/', verbose_name='Фото 6'),
        ),
    ]
