# Generated by Django 4.2 on 2025-05-14 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0003_remove_property_latitude_remove_property_longitude_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='photo_11',
            field=models.ImageField(blank=True, null=True, upload_to='properties/', verbose_name='Фото 11'),
        ),
        migrations.AddField(
            model_name='property',
            name='photo_12',
            field=models.ImageField(blank=True, null=True, upload_to='properties/', verbose_name='Фото 12'),
        ),
        migrations.AddField(
            model_name='property',
            name='photo_13',
            field=models.ImageField(blank=True, null=True, upload_to='properties/', verbose_name='Фото 13'),
        ),
        migrations.AddField(
            model_name='property',
            name='photo_14',
            field=models.ImageField(blank=True, null=True, upload_to='properties/', verbose_name='Фото 14'),
        ),
        migrations.AddField(
            model_name='property',
            name='photo_15',
            field=models.ImageField(blank=True, null=True, upload_to='properties/', verbose_name='Фото 15'),
        ),
        migrations.AddField(
            model_name='property',
            name='photo_16',
            field=models.ImageField(blank=True, null=True, upload_to='properties/', verbose_name='Фото 16'),
        ),
        migrations.AddField(
            model_name='property',
            name='photo_17',
            field=models.ImageField(blank=True, null=True, upload_to='properties/', verbose_name='Фото 17'),
        ),
        migrations.AddField(
            model_name='property',
            name='photo_18',
            field=models.ImageField(blank=True, null=True, upload_to='properties/', verbose_name='Фото 18'),
        ),
        migrations.AddField(
            model_name='property',
            name='photo_19',
            field=models.ImageField(blank=True, null=True, upload_to='properties/', verbose_name='Фото 19'),
        ),
        migrations.AddField(
            model_name='property',
            name='photo_20',
            field=models.ImageField(blank=True, null=True, upload_to='properties/', verbose_name='Фото 20'),
        ),
        migrations.AlterField(
            model_name='property',
            name='sqft',
            field=models.PositiveIntegerField(verbose_name='Площадь (кв. м)'),
        ),
    ]
