# Generated by Django 4.2 on 2025-05-14 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0004_property_photo_11_property_photo_12_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='property',
            name='bedrooms',
        ),
        migrations.AddField(
            model_name='property',
            name='plot_area',
            field=models.PositiveIntegerField(blank=True, help_text='Указывается только для дач', null=True, verbose_name='Площадь участка (соток)'),
        ),
        migrations.AddField(
            model_name='property',
            name='rooms',
            field=models.PositiveIntegerField(default=0, help_text='Общее количество комнат (включая спальни, гостиные и т.д.)', verbose_name='Количество комнат'),
        ),
    ]
