# Generated by Django 4.2 on 2025-05-14 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0005_remove_property_bedrooms_property_plot_area_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='bedrooms',
            field=models.PositiveIntegerField(default=0, verbose_name='Количество спален'),
        ),
    ]
