# Generated by Django 4.2 on 2025-05-14 15:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0006_property_bedrooms'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='property',
            name='photo_1',
        ),
        migrations.RemoveField(
            model_name='property',
            name='photo_10',
        ),
        migrations.RemoveField(
            model_name='property',
            name='photo_11',
        ),
        migrations.RemoveField(
            model_name='property',
            name='photo_12',
        ),
        migrations.RemoveField(
            model_name='property',
            name='photo_13',
        ),
        migrations.RemoveField(
            model_name='property',
            name='photo_14',
        ),
        migrations.RemoveField(
            model_name='property',
            name='photo_15',
        ),
        migrations.RemoveField(
            model_name='property',
            name='photo_16',
        ),
        migrations.RemoveField(
            model_name='property',
            name='photo_17',
        ),
        migrations.RemoveField(
            model_name='property',
            name='photo_18',
        ),
        migrations.RemoveField(
            model_name='property',
            name='photo_19',
        ),
        migrations.RemoveField(
            model_name='property',
            name='photo_2',
        ),
        migrations.RemoveField(
            model_name='property',
            name='photo_20',
        ),
        migrations.RemoveField(
            model_name='property',
            name='photo_3',
        ),
        migrations.RemoveField(
            model_name='property',
            name='photo_4',
        ),
        migrations.RemoveField(
            model_name='property',
            name='photo_5',
        ),
        migrations.RemoveField(
            model_name='property',
            name='photo_6',
        ),
        migrations.RemoveField(
            model_name='property',
            name='photo_7',
        ),
        migrations.RemoveField(
            model_name='property',
            name='photo_8',
        ),
        migrations.RemoveField(
            model_name='property',
            name='photo_9',
        ),
        migrations.AlterField(
            model_name='property',
            name='plot_area',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Площадь участка (соток)'),
        ),
        migrations.AlterField(
            model_name='property',
            name='rooms',
            field=models.PositiveIntegerField(default=0, verbose_name='Количество комнат'),
        ),
        migrations.CreateModel(
            name='PropertyImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='properties/gallery/')),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='properties.property')),
            ],
            options={
                'verbose_name': 'Доп. фото',
                'verbose_name_plural': 'Доп. фотографии',
            },
        ),
    ]
