# Generated by Django 4.2 on 2025-05-14 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0007_remove_property_photo_1_remove_property_photo_10_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='floors',
            field=models.PositiveIntegerField(default=1, verbose_name='Количество этажей'),
        ),
        migrations.AddField(
            model_name='property',
            name='has_balcony',
            field=models.BooleanField(default=False, verbose_name='Балкон'),
        ),
    ]
