# Generated by Django 4.2 on 2025-05-18 12:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0008_property_floors_property_has_balcony'),
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Название города')),
            ],
            options={
                'verbose_name': 'Город',
                'verbose_name_plural': 'Города',
                'ordering': ['name'],
            },
        ),
        migrations.RenameIndex(
            model_name='property',
            new_name='properties__city_id_6c1ba1_idx',
            old_name='properties__city_74fa1a_idx',
        ),
        migrations.AddField(
            model_name='property',
            name='floor_number',
            field=models.PositiveIntegerField(default=1, verbose_name='Этаж'),
        ),
        migrations.AlterField(
            model_name='property',
            name='floors',
            field=models.PositiveIntegerField(default=1, verbose_name='Количество этажей в доме'),
        ),
        migrations.AlterField(
            model_name='property',
            name='city',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='properties', to='properties.city', verbose_name='Город'),
        ),
    ]
