# Generated by Django 4.2 on 2025-05-29 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0009_city_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='bedrooms',
            field=models.PositiveIntegerField(verbose_name='Количество спален'),
        ),
        migrations.AlterField(
            model_name='property',
            name='floors',
            field=models.PositiveIntegerField(verbose_name='Количество этажей в доме'),
        ),
        migrations.AlterField(
            model_name='property',
            name='rooms',
            field=models.PositiveIntegerField(verbose_name='Количество комнат'),
        ),
    ]
