# Generated by Django 4.2 on 2025-05-13 17:45

from django.db import migrations, models
import feedback.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(help_text='Введите полное ФИО', max_length=255, verbose_name='ФИО')),
                ('phone', models.CharField(help_text='Формат: 89876543210', max_length=11, validators=[feedback.models.validate_phone], verbose_name='Телефон')),
                ('email', models.EmailField(blank=True, help_text='Необязательное поле', max_length=255, verbose_name='Email')),
                ('contact_method', models.CharField(choices=[('call', 'Позвонить'), ('email', 'Написать на почту')], max_length=50, verbose_name='Способ связи')),
                ('message', models.TextField(help_text='Опишите интересующие вас услуги', verbose_name='Сообщение')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('is_processed', models.BooleanField(default=False, verbose_name='Обработано')),
            ],
            options={
                'verbose_name': 'Заявка',
                'verbose_name_plural': 'Заявки',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='feedback',
            index=models.Index(fields=['-created_at', 'is_processed'], name='feedback_fe_created_712c59_idx'),
        ),
    ]
