# Generated by Django 4.2 on 2025-05-09 14:34

from django.db import migrations, models
import feedback.models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='feedback',
            options={'ordering': ['-created_at'], 'verbose_name': 'Заявка', 'verbose_name_plural': 'Заявки'},
        ),
        migrations.AlterField(
            model_name='feedback',
            name='email',
            field=models.EmailField(blank=True, help_text='Необязательное поле', max_length=255, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='fullname',
            field=models.CharField(help_text='Введите полное ФИО через пробел', max_length=255, verbose_name='ФИО'),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='message',
            field=models.TextField(help_text='Опишите интересующие вас услуги', verbose_name='Сообщение'),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='phone',
            field=models.CharField(help_text='Формат: +7 (999) 999-99-99', max_length=20, validators=[feedback.models.validate_phone], verbose_name='Телефон'),
        ),
    ]
