# Generated by Django 4.2 on 2025-05-09 15:48

from django.db import migrations, models
import feedback.models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0002_alter_feedback_options_alter_feedback_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='fullname',
            field=models.CharField(help_text='Введите полное ФИО', max_length=255, verbose_name='ФИО'),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='phone',
            field=models.CharField(help_text='Формат: 89876543210', max_length=11, validators=[feedback.models.validate_phone], verbose_name='Телефон'),
        ),
        migrations.AddIndex(
            model_name='feedback',
            index=models.Index(fields=['-created_at', 'is_processed'], name='feedback_fe_created_712c59_idx'),
        ),
    ]
