# Generated by Django 4.2 on 2025-05-08 14:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lighthouse', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='feedback',
            options={'ordering': ['-created_at'], 'verbose_name': 'Обратная связь', 'verbose_name_plural': 'Обратные связи'},
        ),
    ]
