# Generated by Django 4.2 on 2025-05-09 13:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lighthouse', '0003_application_delete_feedback'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Application',
        ),
    ]
